#pragma once

#define SW_UNIVERSAL_SSO_VECTOR_ENABLE_COW 0
#define SW_UNIVERSAL_SSO_VECTOR_NAMESPACE_OPEN namespace sw { namespace universal { namespace internal {
#define SW_UNIVERSAL_SSO_VECTOR_NAMESPACE_CLOSE }}}
#define SW_UNIVERSAL_SSO_VECTOR_IF_COW_ENABLED(...)
#define SW_UNIVERSAL_SSO_VECTOR_IF_COW_DISABLED(...) __VA_ARGS__

#include "universal/internal/container/sso_vector_impl.hpp"

#undef SW_UNIVERSAL_SSO_VECTOR_ENABLE_COW
#undef SW_UNIVERSAL_SSO_VECTOR_NAMESPACE_OPEN
#undef SW_UNIVERSAL_SSO_VECTOR_NAMESPACE_CLOSE
#undef SW_UNIVERSAL_SSO_VECTOR_IF_COW_ENABLED
#undef SW_UNIVERSAL_SSO_VECTOR_IF_COW_DISABLED
